def count_tokens(text: str, model: str = "gpt-4o-mini") -> int: ...
def estimate_cost(prompt_tokens: int, completion_tokens: int, model: str = "gpt-4o-mini") -> dict: ...
def check_context_fit(messages: list[dict], model: str = "gpt-4o-mini", max_output_tokens: int = 4096) -> dict: ...
